"""empty message

Revision ID: 23919b33e3d6
Revises: 
Create Date: 2025-04-22 16:27:11.742192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '23919b33e3d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('czesczamienna',
    sa.Column('czesc_id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('numer_seryjny', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('cena', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dostepnosc', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('czesc_id')
    )
    op.create_table('klient',
    sa.Column('klient_id', sa.Integer(), nullable=False),
    sa.Column('imie', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nazwisko', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nr_telefonu', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('adres', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('klient_id')
    )
    op.create_table('pracownik',
    sa.Column('pracownik_id', sa.Integer(), nullable=False),
    sa.Column('imie', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nazwisko', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('stanowisko', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('pracownik_id')
    )
    op.create_table('pojazd',
    sa.Column('pojazd_id', sa.Integer(), nullable=False),
    sa.Column('klient_id', sa.Integer(), nullable=False),
    sa.Column('marka', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('rok_produkcji', sa.Integer(), nullable=False),
    sa.Column('numer_rejestracyjny', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('vin', sqlmodel.sql.sqltypes.AutoString(length=17), nullable=False),
    sa.ForeignKeyConstraint(['klient_id'], ['klient.klient_id'], ),
    sa.PrimaryKeyConstraint('pojazd_id')
    )
    op.create_table('zlecenieserwisowe',
    sa.Column('zlecenie_id', sa.Integer(), nullable=False),
    sa.Column('pojazd_id', sa.Integer(), nullable=False),
    sa.Column('pracownik_id', sa.Integer(), nullable=False),
    sa.Column('data_zlecenia', sa.Date(), nullable=False),
    sa.Column('opis_problemu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wykonane_naprawy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('koszt_calkowity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pojazd_id'], ['pojazd.pojazd_id'], ),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownik.pracownik_id'], ),
    sa.PrimaryKeyConstraint('zlecenie_id')
    )
    op.create_table('uzycieczesci',
    sa.Column('uzycie_id', sa.Integer(), nullable=False),
    sa.Column('zlecenie_id', sa.Integer(), nullable=False),
    sa.Column('czesc_id', sa.Integer(), nullable=False),
    sa.Column('ilosc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['czesc_id'], ['czesczamienna.czesc_id'], ),
    sa.ForeignKeyConstraint(['zlecenie_id'], ['zlecenieserwisowe.zlecenie_id'], ),
    sa.PrimaryKeyConstraint('uzycie_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uzycieczesci')
    op.drop_table('zlecenieserwisowe')
    op.drop_table('pojazd')
    op.drop_table('pracownik')
    op.drop_table('klient')
    op.drop_table('czesczamienna')
    # ### end Alembic commands ###
